Files for example added
OpenCMISS-Examples/diffusion_equation pull request #1
Opened 2017-10-15 01:22 UTC by kmith

Modified "diffusion_equation" example conforming to new format.

2017-10-15 23:29 UTC, hsorby requested changes
Looks good creating a verify section would make this up-to-date with the current template and we could merge it in then.

2017-10-15 23:29 UTC, hsorby commented on README.rst
> +Results can be visualised by running `visualise.com <./src/fortran/visualise.com>`_ with the `Cmgui visualiser <http://physiomeproject.org/software/opencmiss/cmgui/download>`_.
Could make this into a  [verify section](https://github.com/OpenCMISS-Examples/template_example/blob/master/README.template.rst#verifying-the-example) and add a comment on how the expected results are available.

2017-10-15 23:30 UTC, chrispbradley commented
And maybe change visualize.com to visualize.cmgui???

2017-10-16 03:42 UTC, hsorby approved these changes
Great looks good.

2017-10-16 03:43 UTC, merged